"""Project generation engine."""

from __future__ import annotations

import json
from pathlib import Path

from .models import CompileResult, GeneratedFile, ProjectPlan
from .planner import build_plan
from .safety import assert_safe_relative_path, escape_markdown, redact_secrets


def _render_plan_markdown(plan: ProjectPlan) -> str:
    task_lines = []
    for task in plan.tasks:
        task_lines.append(
            "\n".join(
                (
                    f"### {task.priority.value}: {escape_markdown(task.title)}",
                    f"- Nguyên nhân: {escape_markdown(task.reason)}",
                    f"- Cách sửa: {escape_markdown(task.fix)}",
                    f"- File liên quan: {', '.join(task.files)}",
                    f"- Mức độ ảnh hưởng: {escape_markdown(task.impact)}",
                )
            )
        )
    return "\n\n".join(task_lines)


def _project_files(plan: ProjectPlan, requirements: str) -> list[GeneratedFile]:
    safe_requirements = escape_markdown(redact_secrets(requirements))
    readme = f"""# {escape_markdown(plan.name)}

{escape_markdown(plan.summary)}

## Stack

{escape_markdown(plan.stack)}

## Features inferred from input

{chr(10).join(f"- {escape_markdown(feature)}" for feature in plan.features)}

## Implementation plan

{_render_plan_markdown(plan)}

## Run

```bash
python -m venv .venv
. .venv/bin/activate
pip install -e .[dev]
python -m {plan.slug.replace("-", "_")} --help
```

## Source requirements snapshot

```text
{safe_requirements[:4000]}
```
"""
    pyproject = f"""[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{plan.slug}"
version = "0.1.0"
description = "Generated by Universal Project Compiler Agent"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8,<9"]

[tool.setuptools]
package-dir = {{"" = "src"}}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
"""
    package = plan.slug.replace("-", "_")
    return [
        GeneratedFile(Path("README.md"), readme),
        GeneratedFile(Path("pyproject.toml"), pyproject),
        GeneratedFile(Path("src") / package / "__init__.py", "__version__ = '0.1.0'\n"),
        GeneratedFile(
            Path("src") / package / "__main__.py",
            """from __future__ import annotations


def main() -> None:
    print("Project scaffold is ready. Read README.md for the implementation plan.")


if __name__ == "__main__":
    main()
""",
        ),
        GeneratedFile(
            Path("tests") / "test_smoke.py",
            f"""from {package} import __version__


def test_version() -> None:
    assert __version__ == "0.1.0"
""",
        ),
        GeneratedFile(Path("docs") / "PLAN.md", _render_plan_markdown(plan) + "\n"),
        GeneratedFile(
            Path("scripts") / "start.sh",
            "#!/usr/bin/env sh\nset -eu\npython -m " + package + "\n",
        ),
    ]


def compile_project(
    requirements: str, output_dir: Path, project_name: str | None = None
) -> CompileResult:
    """Compile requirements into a concrete project directory."""

    plan = build_plan(requirements, project_name)
    root = output_dir / plan.slug
    root.mkdir(parents=True, exist_ok=True)
    files = _project_files(plan, requirements)
    for generated in files:
        assert_safe_relative_path(generated.path)
        target = root / generated.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated.content, encoding="utf-8")
        if target.name.endswith(".sh"):
            target.chmod(0o755)
    manifest = {
        "name": plan.name,
        "slug": plan.slug,
        "stack": plan.stack,
        "files": [str(file.path) for file in files],
    }
    (root / "compile-manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return CompileResult(
        plan=plan,
        root=root,
        files=[*files, GeneratedFile(Path("compile-manifest.json"), json.dumps(manifest))],
    )
